### ISSUE TITLE
Deprecated redirect syntax

### ISSUE THREAD

**Issue by georgeben** [shalvah/twittersignin#2]
Hey shalvah, the express redirect syntax used in the README, 
```js
res.redirect(`https://api.twitter.com/oauth/authorize?oauth_token=${requestToken}`, 302);
``` 
has been deprecated. According to the [express documentation](https://expressjs.com/en/4x/api.html#res.redirect), it should be 
```js
res.redirect([status,] path)
```

Thanks.

**Comment by shalvah** [comment]
Thanks, fixed.👍

**Comment by arielger** [comment]
It looks like it is still using the old arguments order.
