### ISSUE TITLE
Why require accessToken?

### ISSUE THREAD

**Issue by phuctm97** [shalvah/twittersignin#8]
This library helps do Twitter Sign In, which should be done with just application credentials, not user credentials. Why does it require `accessToken` and `accessTokenSecret`.

I saw you're using `twit` which has an option `app_only_auth: true` to authenticate only the app. Any reason that I missed?

**Comment by shalvah** [comment]
Er, does it *require* it? Idk, it's just there; you can set them to null and the library won't complain. But you can send in a PR to update the JSDoc so it doesn't complain unnecessarily for those using TypeScript.

**Comment by phuctm97** [comment]
Yeah, it requires, `Twit` throws exceptions when I don't set `accessToken` and `requestToken`, it requires `app_only_auth: true`.
